name: CI Python App

on:
  push:
    paths:
      - 'app_python/**'
  pull_request:
    paths:
      - 'app_python/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd app_python
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Linter (flake8)
        run: |
          cd app_python
          pip install flake8
          flake8 .

      - name: Run Unit Tests
        run: |
          cd app_python
          python -m unittest discover -v

      # Docker steps
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          cd app_python
          docker build -t your-dockerhub-user/python-app:latest .
          docker push your-dockerhub-user/python-app:latest

      - name: Snyk Security Scan
        uses: snyk/actions/docker@master
        with:
          image: your-dockerhub-user/python-app:latest
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}